version: '3'

services:
  mlsploit-execution-service:
    build:
      context: .
      args:
        - BASE_DIR=$PWD
    network_mode: host
    extra_hosts:
      - 'api-host:127.0.0.1'
      - 'redis-host:127.0.0.1'
      - 'rabbitmq-host:127.0.0.1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    env_file:
      - .env
    environment:
      RUNNING_IN_DOCKER: 'true'
