version: '3'

services:
  mlsploit-networking-backend-service:
    image: redis:latest
    ports:
      - 6379:6379

  mlsploit-networking-broker-service:
    build: ./docker-services/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
